name: at_challenge
description: A Flutter application implementing the at protocol.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  page_transition: "^1.1.7+2"
  flutter_svg: 0.18.0
  flutter_spinkit: ^4.1.2+1
  provider: ^4.3.2+2
  cupertino_icons: ^0.1.3

  # @ Protocol dependencies:
  path_provider: ^1.5.1
  at_demo_data: ^0.0.2
  at_client_mobile: ^1.0.0
  modal_progress_hud: any



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/
    - assets/img/machango.svg
    - assets/img/clouds.svg
    - assets/img/mood_happy.svg
    - assets/img/mood_neutral.svg
    - assets/img/mood_sad.svg

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
    - family: MerriweatherSans
      fonts:
        - asset: assets/fonts/MerriweatherSans-VariableFont_wght.ttf
